### ISSUE TITLE
NUMT Copy Number Estimation

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/svaNUMT#4]
Could you add an example to the vignette showing how estimate NUMT copy number? I would like to figure out how many copies there are on the non-mitochondrial chromosomes, to decide whether or not heteroplasmy could reliably be estimated from the sample.

**Comment by jackieduckie** [comment]
Hi @DarioS,  svaNUMT identifies the presence of NUMTs by SV breakpoints from the input SV calls (VCF). Whether copy numbers can be inferred depends on upstream SV calls. But maybe I didn't quite understand the context of your question, could you explain what you mean by copies of NUMTs? Is it copies of the same MT sequence inserted into different nuclear chromosome loci?

> Could you add an example to the vignette showing how estimate NUMT copy number? I would like to figure out how many copies there are on the non-mitochondrial chromosomes, to decide whether or not heteroplasmy could reliably be estimated from the sample.

**Comment by jackieduckie** [comment]
If I understood the question correctly, you would like to infer copy number by the non-reference MT sequences in nuclear chromosomes to calculate heteroplasmy? If the first step is to collect all the MT sequences in NUMTs, it can be done by applying the GRanges from gr$known$MT and gr$MT$MT to the reference MT genome (e.g. the bioconductor BSgenome libraries combined with the getseq() function), or if available from the upstream sv calls, gr$insSeq$insSeq.

**Comment by DarioS** [comment]
Yes, so the next step would be to estimate the copy number of each one. Could there be a convenience function to do it all?

**Comment by jackieduckie** [comment]
My experience with NUMTs is that there are usually not many of them and the MT sequences can be a segment from anywhere on the MT genome. To estimate copies from NUMT sequences I'd think it would make sense to look for specific mutations in them. That said MT sequences in NUMT vary wildly in lengths so it might not be enough. Identifying mutations in NUMT MT sequences is beyond svaNUMT (at least in the current version) but I reckon a quick pairwise alignment or SV VAF should give you misalignment profiles of the MT sequences? For inferring the fractions of mutations in SVs, SVClone may be a relevant tool. We'll consider CN estimation as a future feature.

**Comment by jbedo** [comment]
Not sure how easy this would be to do in a general way, afaik breakpoint
depth information isn't standardised for SVs. Which caller are you using?

**Comment by DarioS** [comment]
GRIDSS 2, of course!
