### ISSUE TITLE
Obtaining Known NuMTs for hg38

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/svaNUMT#6]
It looks like numtS.txt is for hg19. Could the package also provide the same database for hg38? Also,

```r
colnames(numtS) <- c("bin", "seqnames", "start", "end", "name", "score", "strand")
```
Perhaps the column names could be in the text file so this is unnecessary? Ideally, there would be a genome parameter which the user could specify (e.g. `genome = "hg19"`) and the setup steps (e.g. getting `genome$chrMT`) would all be done in one command.

**Comment by jackieduckie** [comment]
Apologies for the late reply. Thanks for the comment on including a genome parameter. The setup steps will certainly be simplified in the next version.
 
numtS.txt is extracted from the UCSC NumtS sequence [link](http://genome.ucsc.edu/cgi-bin/hgTables?db=hg19&hgta_group=rep&hgta_track=numtSeq&hgta_table=numtS&hgta_doSchema=describe+table+schema). There is no official NumtS sequence for hg38 at the moment so the best one can do now is to run LiftOver on the hg19 sequences.
