### ISSUE TITLE
ask and update options does NOT work with BiocManager::install

### ISSUE THREAD

**Issue by rgaiacs** [PapenfussLab/svaNUMT#7]
```
> BiocManager::install("PapenfussLab/svaNUMT", ask=FALSE, update=FALSE)
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: rlang     (1.0.4 -> 1.0.5) [CRAN]
5: pillar    (1.8.0 -> 1.8.1) [CRAN]
6: lifecycle (1.0.1 -> 1.0.2) [CRAN]
7: cli       (3.3.0 -> 3.4.0) [CRAN]
8: httr      (1.4.3 -> 1.4.4) [CRAN]
9: stringr   (1.4.0 -> 1.4.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
```

**Comment by jackieduckie** [comment]
svaNUMT has not been tested with the newer versions of the packages listed but I think it would be ok if you updated all of these packages. However, please let me know if there is an issue.

**Comment by rgaiacs** [comment]
@jackieduckie Thanks for the fast reply. I want to skip the update. For other packages, when I run

```
BiocManager::install("foo", ask=FALSE, update=FALSE)
```

the installation will skip the update question but for

```
BiocManager::install("PapenfussLab/svaNUMT", ask=FALSE, update=FALSE)
```

it still ask the question.

I'm not familiar with Bioconductor Manager. Maybe this is because the package is in GitHub?

**Comment by rgaiacs** [comment]
It's a bug already reported upstream: https://github.com/Bioconductor/BiocManager/issues/126
